// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLdKB9kwOMmL1SZU08gcR8PxxWY_iCsao',
    appId: '1:556380406835:web:fd30013805377a6614cf46',
    messagingSenderId: '556380406835',
    projectId: 'storify',
    authDomain: 'storify-50031.firebaseapp.com',
    databaseURL: 'https://storify-50031.firebaseio.com',
    storageBucket: 'storify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-JMe6Ddfeyi201RLPcwmTpycvgnm-H0',
    appId: '1:556380406835:android:66b9c98d9ee86ba014cf46',
    messagingSenderId: '556380406835',
    projectId: 'storify',
    databaseURL: 'https://storify-50031.firebaseio.com',
    storageBucket: 'storify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtl1yx040Id6SPFYAYTPHpLAMTfk1D9Vk',
    appId: '1:556380406835:ios:ed08f3bfe8240dc914cf46',
    messagingSenderId: '556380406835',
    projectId: 'storify',
    databaseURL: 'https://storify-50031.firebaseio.com',
    storageBucket: 'storify.appspot.com',
    androidClientId: '556380406835-82783ttmubhn9ame256ofjo2lcbpgojg.apps.googleusercontent.com',
    iosClientId: '556380406835-emt2q500koio1gioqc1lu0df3q96bpvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
